# Generated by Django 6.0.5 on 2026-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='q10',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='q6',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='q7',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='q8',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='q9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='addiction_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='q5',
            field=models.IntegerField(default=1),
        ),
    ]
