name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12


      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt


      - name: Django Check
        run: |
          cd backend
          python manage.py check


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install


      - name: Build Frontend
        run: |
          cd frontend
          npm run build


      - name: Docker Build
        run: |
          docker compose build


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}

          username: ${{ secrets.EC2_USER }}

          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd Instamind

            git pull

            sudo docker compose down

            sudo docker compose up -d --build